(define (domain BLOCKS)  
    (:requirements :strips :typing :equality)  
    (:types block hand colour - object)  
    (:predicates (on ?x - block ?y - block)  
                 (ontable ?x - block)       
                 (clear ?x - block)       
                 (handempty)     
                 (holding ?x - block)    
                 
                 ;colour related
                 (coloured ?h - hand ?c - colour)
                 (block-colour ?x - block ?c - colour)
                 (washed ?h - hand)
    )  
    (:action wash-hand     
        :parameters (?h - hand)     
        :precondition (and (not (washed ?h))
                           (handempty)
                      )
        :effect       (washed ?h)
    ) 
    (:action pick-up     
        :parameters (?x - block ?c - colour ?h - hand)     
        :precondition (and (clear ?x) 
                           (ontable ?x) 
                           (handempty)
                           
                           ;colour related
                           (block-colour ?x ?c)
                           (or (washed ?h)
                               (coloured ?h ?c)
                           )
                      )     
        :effect       (and (not (ontable ?x))   
                           (not (clear ?x))   
                           (not (handempty))   
                           (holding ?x)
                           
                           ;colour related
                           (coloured ?h ?c)
                           (not (washed ?h))
                      )
    )  
    (:action put-down     
        :parameters (?x - block)     
        :precondition (holding ?x)     
        :effect       (and (not (holding ?x))   
                           (clear ?x)   
                           (handempty)   
                           (ontable ?x)
                      )  
    )   
    (:action unstack     
        :parameters (?x - block ?y - block ?c - colour ?h - hand)     
        :precondition (and (on ?x ?y) 
                        (clear ?x) 
                        (handempty)
                        (block-colour ?x ?c)
                        (or (washed ?h)
                            (coloured ?h ?c)
                        )
                    )     
        :effect     (and (holding ?x)   
                        (clear ?y)   
                        (not (clear ?x))   
                        (not (handempty))   
                        (not (on ?x ?y))
                        (coloured ?h ?c)
                        (not (washed ?h))
                    )
    )                    
    (:action stack     
        :parameters (?x - block ?y - block)     
        :precondition (and (holding ?x) 
                           (clear ?y)
                      ) 
        :effect       (and (not (holding ?x))   
                        (not (clear ?y))   
                        (clear ?x)   
                        (handempty)   
                        (on ?x ?y)
        )
    ) 
)